apiVersion: v1
kind: Service
metadata:
  name: ssjnmghjhvb 
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ssjnmghjhvb "
    port: 8080
  selector:
    app: ssjnmghjhvb 
